### ISSUE TITLE
any plan to release for new versions

### ISSUE THREAD

**Issue by tamoj32** [nopSolutions/eway-plugin-for-nopcommerce#4]
Do you have any plan to work on NOPCommerce new versions like 4.2 ... 4.5

**Comment by AndreiMaz** [comment]
Please see our comment at https://github.com/nopSolutions/eway-plugin-for-nopcommerce

nopCommerce team doesn't plan to upgrade this plugin to the latest version. Our community is more than welcome to continue development of the plugin. Please feel free to use our source code.

Our third-party vendors already upgraded this plugin to the latest version. You can find it on our marketplace
